version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/Forum
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-g*i#g8s+b$$313t(5&aqq#^z#glfk1k^++35w0c-2_m-#g0t&@$$"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: